### ISSUE TITLE
Create the twitter bot

### ISSUE THREAD

**Issue by edsun123** [codeforboston/flagging#19]
Creating the script that retrieves the output of the flask website (whether or not the river is safe). Does not connect to database. (Edwin Sun)

**Comment by edsun123** [comment]
Currently just posts notifications in twitter. Needs keys.

**Comment by edsun123** [comment]
Reminder: should finish when the database is setup and ask client what tweets they want to sent out. 
Reminder: keys needs to be saved in the vault.zip (must modify the json file) and add/save a variable to hold the variables

**Comment by dwreeves** [comment]
Status on this: this is very much a final stage thing, but we still plan on doing it because it's kinda cool, so why not?

We'll probably create our own Twitter bot as opposed to hooking up to the CRWA's account, but we'll parametrize the credentials so that it's possible to hook up to any Twitter account.

To make things simple, the twitter bot will run as part of the `update_database()` function.

**Comment by dwreeves** [comment]
Status on this: Twitter bot is up but is very basic. I think we'll roll with it for now.

Note to self is that we should add the link to the website when there are advisories. Unfortunately the top-level domain seems to comes from the request context? If `url_for('flagging.index', _external=True)` doesn't work then we might need to hardcode the TLD.
