### ISSUE TITLE
Add unit-test to test data is up-to-date.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#37]
There is a weird issue with HOBOlink where it splits the data off into multiple columns.

Here is a CSV direct from a HOBOlink export:

![image](https://user-images.githubusercontent.com/31971762/86862165-aab77a80-c096-11ea-90ce-7be4444cdf18.png)

Yes, it's very strange.

Our code has fixed this issue-- it uses some Pandas magic to identify the first nonmissing value within a row that matches to a subset of column names.

With that said, we want to make sure we're unit-testing in a way that could have detected this issue, so going forward we can snuff out anything like this.

We want to assert that the _last row_ of a HOBOlink dataframe (returned by `get_hobolink_data()`) contains a timestamp that is no more than 30 minutes later than the current EST time. We can also do the same for the USGS data (30 minutes). For the fully pre-processed and joined data, I would make that interval 2 hours due to how we group data only after a full hour's worth of data is in.

**Comment by dfe325** [comment]
Taking a look at this.

**Comment by dfe325** [comment]
Here's what I got so far: ([https://github.com/codeforboston/flagging/compare/master...dfe325:dev_unit-test-data])

I hard-coded in the vars that seemed useful from hobolink.py to get a response from hobolink.Trying to successfully return a 200 before proceeding to actually testing the column/final row in the dataframe object. 

This gives me an error because it doesn't know what the value of get_keys()['HOBOLINK'] is (tried poking around in the app and enviro vars but no luck). I'm assuming this needs these creds to run and there is no effective way to simulate this for the purposes of what we want to test.

**Comment by dwreeves** [comment]
I'm confused by the class `TestData`. What's the class supposed to be doing?

Also, you don't need to recreate the wheel-- just use the functions in the code that get the data; you don't need to make a new one.

**Comment by dfe325** [comment]
Ok, new version is up: https://github.com/codeforboston/flagging/compare/master...dfe325:dev_unit-test-data

- Eliminated `TestData` (added a class bc I was anticipating adding multiple tests - first to confirm functions were working, then to test the actual data, but am just testing data now)

-Using the current function to test that the last timestamp is within 30 minutes:
`last_timestamp.minute - datetime.now().minute < 30`

This needs one more pass though... it doesn't account for what happens when the hours are different (e.g. last_timestamp = 7:02:00 and datetime.now().minute is 6:59:00) but I have an idea of how to solve this.

**Comment by dwreeves** [comment]
The Pytest framework tends to use functions and decorators, not directly-initiated custom classes. It's rare you'll use classes when using Pytest. Pytest is compatible with `unittest.TestCase`, but it's rare you'll ever need it and you don't need it here. If you saw any examples of unit-testing in Python that you were copying from, check to see whether it was from the base unittest base module or Pytest.

Anyway, that's no big deal... because what you have now is _REALLY_ close! 😮 Wow!

Here are my notes:

(1)

`last_timestamp = df.iloc[-1][0]` <-- the `iloc[-1]` is correct. Good job! We are assuming that the dataframe is sorted by timestamp, but I told you to assume that and we will continue to assume it, as the sorting of values by timestamp makes everything a lot easier. (We can eventually test this too!)

The `[0]` technically works but is dangerous. The reason why it's dangerous is because we don't want to rely on the order of the columns if we don't need to. I don't think it'd be fair of me to torture you with trying to figure out the Pandas API on your own, as it's a clunky mess (I love it, but it's not friendly to people just getting started with it). So I'll just give you the answer:

```python
last_timestamp = df['time'].iloc[-1]
```

Basically, first you want to select the column `time` not based on its position but its name, and this does that. I also suggest selecting the column before the row, as this is more idiomatic and familiar in the realm of Pandas code.

(2)

`assert (last_timestamp.minute - datetime.now().minute) < 30` <-- Right idea, but wrong execution. The `minute` label is a number between 0-60:

![image](https://user-images.githubusercontent.com/31971762/87875154-2d94db00-c99d-11ea-9042-08a495a0cdaf.png)

What you actually want is to take the difference between two full datetimes, and then convert that time-delta into minutes. Don't convert to minutes until _after_ you've taken the difference between the two datetimes. In other words, you want "minutes" of the time _deltas_ not the times themselves. Does that make sense?

**Comment by dfe325** [comment]
Gotcha, thanks! Always super helpful to know what the conventions are and what is a more or less "dangerous" implementation. I agree with using column headings rather than index. For the column heading I initially was trying to make it work with "Time, GMT -04:00" but wasn't having any luck so did the index instead, will make the change back though. 

And timedeltas make sense! Taking the difference between two full datetimes would solve for the hours and also account for another edge case that was bugging me, namely what if (for some reason) the dates are different? I'm trying to do the timedelta thing today but have to step away for a bit. Will send an update, hopefully with the full solution, tonight.
