### ISSUE TITLE
`dev_postgres`: Set up Postgres database in Heroku.

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#54]
I'm not really sure how to set up a Postgres database in Heroku. Can someone figure this out?

If it involves any files or code that Heroku reads, commit them in. If it involves some set-up, add a doc to the `/docs` folder explaining the setup required, or modify the `deployment.md` file to include that setup as part of the deployment.

For this and other Heroku-related tasks, create your own staging environment for the app using your own Heroku account (it's free if you don't have one!) and try to make it work on your own deployment of the app.

**Comment by edsun123** [comment]
I can take a look at this

**Comment by edsun123** [comment]
This issue is open to anybody:

As for general steps:
1) create a heroku app
2) attach postgress database addon ( command is in this link https://devcenter.heroku.com/articles/heroku-postgresql)
3) export the heroku database url to local environment variable (to get config vars: https://devcenter.heroku.com/articles/heroku-postgresql)
4) set the database database urls with the needed environment variables for local application (i.e. password)  (to set config vars: https://devcenter.heroku.com/articles/heroku-postgresql)
5) If you run into problem that the database cannot find the table, initialize the table inside the heroku postgres with heroku pg:psql. 
6) run the application with heroku open
