### ISSUE TITLE
Automatically detect pages inside the app as a parametrized text fixture

### ISSUE THREAD

**Issue by dwreeves** [codeforboston/flagging#55]
Right now the `test_pages` function loops through a manually defined list of pages that exist within the app.

Can we actually create a list of pages from the `app` instance itself? And then use each element in that list as an input to the `test_pages` function?

The way to do that is: get a list of all the available routes within the app, and then loop over it. But you need to do this as a "parametrized fixture": https://docs.pytest.org/en/stable/parametrize.html I would call this fixture `routes`. The new `routes` fixture would itself needs to take the `app` fixture as an argument, and then `yield` each `route` in the app instance. And then, each `route` would be a parametrized argument for the `test_pages` function.

Once that's all done, we'll be able to test whether or not a page breaks by loading it simply based on the fact that it's attached to the website. So we don't need to remember to constantly update the `test_pages` function.

At the present moment, for all (non-static) routes, the behavior of the test function should be exactly the same as before, because all routes are accounted for in the `pytest.mark.parametrize` decorator. In the future though, if we add another page to the site, then it should automatically detect that we did that and it should test that it returns a non-400 / non-500 status code when you do a GET request to it.

Use the `dev2` branch for this task, as it's the most up-to-date version of the app right now.

**Comment by bancona** [comment]
I'll give this a shot!

**Comment by bancona** [comment]
@dwreeves If I'm understanding correctly, this won't work as described above because pytest creates a fixed number of test cases based on tests' parameterizations at "collection" time, which occurs before fixtures are run. ([Long thread that touches on this issue](https://github.com/pytest-dev/pytest/issues/349).) If we knew in advance how many pages there were, we could parameterize the fixture with a list of params of that size so that pytest makes the correct number of test cases, but that would defeat the purpose of this fixture. 

A less pretty solution would simply be to have the fixture return a list of all routes, which the test would then have to iterate over, though this forces some work/clutter to keep track of which routes fail the test (unless we're happy simply failing on the first route failure of the test).

What do you think?

Sidenote: how might I run the tests without the vault password? Or if I need it, could I have access to it?

**Comment by dwreeves** [comment]
Excellent sleuthing. I hadn't realized that would be a problem, but I do see why it is a problem.

I don't like unparametrizing the test because it doesn't give good feedback to the person running the test about what went wrong.

I would say there are two feasible options.

1. Keep as-is, and just 

2. Borrow the `unittest` approach to the problem of parametrization ("subtests") via using another dependency: https://pypi.org/project/pytest-subtests/ The reason why this approach works is because the parametrization is determined at the runtime of the test itself, not prior to it.

I'm fine with either. Although from a project management perspective I sort of prefer option 1-- I can force people to edit the `./tests` dir as a requirement for submitting stuff into the project, which increases the salience of testing among project contributors. What are your thoughts?

**Comment by bancona** [comment]
I like the idea of requiring people to add testing for new/modified pages, and with that requirement maintaining a list of all routes shouldn't pose much of a problem, plus some pages should have additional tests anyway, especially if they require parameters of some kind (for which the fixture approach wouldn't work as it wouldn't know what parameters to provide)

**Comment by dwreeves** [comment]
Oh yeah, pages will definitely get their own unit-tests soon. Just checking that the status code is <400 isn't really sufficient for making sure the website's behavior is intended.

Thanks for your feedback and for looking into this! Let's close this.
